### ISSUE TITLE
Required minimum chars for phone number field

### ISSUE THREAD

**Issue by MattiaPrimavera** [Instant-Visio/InstantVisio-AndroidApp#20]
How many numbers do we need at least ? Even better would be checking the number is valid according to the country

**Comment by HugoGresse** [comment]
a valid number for France is "18" which is not OK to send an SMS too. 
On the web we've decided to 6 char.

**Comment by HugoGresse** [comment]
the number is also checked on the back before sending the sms too.

**Comment by MattiaPrimavera** [comment]
> is not OK to send an SMS too.

What do you mean ?

**Comment by MattiaPrimavera** [comment]
> the number is also checked on the back before sending the sms too.

Do you send back an API error in case the number is not valid ? If the user is not correctly invited, there's no use in opening the room and lead the user to the `VideoCall` screen

**Comment by MattiaPrimavera** [comment]
checked with @HugoGresse: must not specify the phone number when calling firebase in order to avoid sending the sms

**Comment by HugoGresse** [comment]
> > is not OK to send an SMS too.
> 
> What do you mean ?

you don't want to send a SMS to the police or the firefighters



> > the number is also checked on the back before sending the sms too.
> 
> Do you send back an API error in case the number is not valid ? If the user is not correctly invited, there's no use in opening the room and lead the user to the `VideoCall` screen

I thing it will throw an error and you'll need to catch it.

**Comment by HugoGresse** [comment]
test
